### ISSUE TITLE
bitbake erro

### ISSUE THREAD

**Issue by xueliu** [tano-systems/meta-tanowrt#1]
Hello,

I am tring to compile tanowrt for rpi3. But I have errors in the last step `MACHINE=rpi3 bitbake tanowrt-image-full` or input `bitbake`

```
23:56 $ bitbake
ERROR: Unable to start bitbake server (None)
ERROR: Server log for this session (/home/lx/workspace/tanowrt/build/bitbake-cookerdaemon.log):
--- Starting bitbake server pid 29350 at 2020-02-05 23:56:55.268686 ---
ERROR: Layer directory '/home/lx/workspace/tanowrt/meta-raspberrypi' does not exist! Please check BBLAYERS in /home/lx/workspace/tanowrt/build/conf/bblayers.conf

```
Thanks
Host OS: elementary OS

**Comment by namedun** [comment]
Looks like you didn't clone the meta-raspberrypi layer into the working directory. Follow the build instructions  outlined in [README.md](https://github.com/tano-systems/meta-tanowrt/blob/master/meta-tanowrt-hsl-rpi/README.md).

**Comment by xueliu** [comment]
I did followed the instructions in [README.md](https://github.com/tano-systems/meta-tanowrt/blob/master/meta-tanowrt-hsl-rpi/README.md)
the components what I have after `TEMPLATECONF=meta-tanowrt/meta-tanowrt-hsl-rpi/templates . ./oe-init-build-env` :
```
bitbake  LICENSE               LICENSE.MIT  meta-openembedded  meta-selftest  meta-tanowrt       README.LSB      README.qemu
build    LICENSE.GPL-2.0-only  meta         meta-rapsberrypi   meta-skeleton  oe-init-build-env  README.OE-Core  scripts
```

**Comment by namedun** [comment]
Thanks for the report.

It was a typo in `meta-tanowrt-hsl-rpi/manifests/deps.xml`. The `meta-raspberrypi` layer was cloned to the wrong directory `meta-rapsberrypi`. Fixed in the master branch.

You can simply rename the `meta-rapsberrypi` directory to `meta-raspberrypi` or perform the initialization procedure again.
