### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by xueliu** [tano-systems/meta-tanowrt#2]
Hello Anton Kikin,

I got a new error. Sorry I can not format the error message very well.cd 

23:57 $ MACHINE=rpi3 bitbake tanowrt-image-full
Loading cache: 100% |#############################################################################################################################################################################| Time: 0:00:00
Loaded 19 entries from dependency cache.
ERROR: /home/lx/workspace/tanowrt/meta-tanowrt/meta-tanowrt/recipes-tano/tano/tano-version.bb: Error executing a python function in <code>:                                                      | ETA:  --:--:--

The stack trace of python calls that resulted in this exception/failure was:
File: '<code>', lineno: 12, function: <module>
     0008:__anon_25__home_lx_workspace_tanowrt_meta_classes_debian_bbclass(d)
     0009:__anon_35__home_lx_workspace_tanowrt_meta_classes_devshell_bbclass(d)
     0010:__anon_130__home_lx_workspace_tanowrt_meta_classes_sstate_bbclass(d)
     0011:__anon_20__home_lx_workspace_tanowrt_meta_classes_blacklist_bbclass(d)
 *** 0012:__anon_68__home_lx_workspace_tanowrt_meta_tanowrt_meta_tanowrt_classes_tano_scmrevision_bbclass(d)
File: '/home/lx/workspace/tanowrt/meta-tanowrt/meta-tanowrt/classes/tano-scmrevision.bbclass', lineno: 67, function: __anon_68__home_lx_workspace_tanowrt_meta_tanowrt_meta_tanowrt_classes_tano_scmrevision_bbclass
     0063:    tano_base = d.getVar('TANOWRT_BASE')
     0064:    repo_base = os.path.normpath(os.path.join(tano_base, ".."))
     0065:    mark_recipe_dependencies(repo_base, d)
     0066:    d.setVar('TANOWRT_SCM_REVISION', get_git_revision(repo_base))
 *** 0067:    d.setVar('TANOWRT_SCM_BRANCH', get_git_branch(repo_base))
     0068:}
File: '/home/lx/workspace/tanowrt/meta-tanowrt/meta-tanowrt/classes/tano-scmrevision.bbclass', lineno: 28, function: get_git_branch
     0024:def get_git_branch(p):
     0025:    import subprocess
     0026:
     0027:    try:
 *** 0028:        ref = gitrev_run("git symbolic-ref -q HEAD", p)
     0029:        return os.path.basename(ref)
     0030:    except OSError:
     0031:        return None
     0032:
File: '/home/lx/workspace/tanowrt/meta-tanowrt/meta-tanowrt/classes/tano-scmrevision.bbclass', lineno: 13, function: gitrev_run
     0009:# (git://git.openembedded.org/meta-openembedded)
     0010:#
     0011:
     0012:def gitrev_run(cmd, path):
 *** 0013:    (output, error) = bb.process.run(cmd, cwd=path)
     0014:    return output.rstrip()
     0015:
     0016:def get_git_revision(p):
     0017:    import subprocess
File: '/home/lx/workspace/tanowrt/bitbake/lib/bb/process.py', lineno: 182, function: run
     0178:        if not stderr is None:
     0179:            stderr = stderr.decode("utf-8")
     0180:
     0181:    if pipe.returncode != 0:
 *** 0182:        raise ExecutionError(cmd, pipe.returncode, stdout, stderr)
     0183:    return stdout, stderr
Exception: bb.process.ExecutionError: Execution of 'git symbolic-ref -q HEAD' failed with exit code 1

ERROR: Failed to parse recipe: /home/lx/workspace/tanowrt/meta-tanowrt/meta-tanowrt/recipes-tano/tano/tano-version.bb

Summary: There were 2 ERROR messages shown, returning a non-zero exit code.

**Comment by namedun** [comment]
Fixed in master branch.
