### ISSUE TITLE
Error compiling due to missing luadist2.... luadist2 no longer available on github

### ISSUE THREAD

**Issue by jenswes** [tano-systems/meta-tanowrt#3]
Hi,

<code>
luasyslog-1.0.0-2-tano1 do_fetch: Failed to fetch URL git://github.com/LuaDist2/luasyslog.git

</code>

yesterfay google shows a log github links, all error 404, todal all lings are gone

any mirror somewhere?

thanks,
jens

**Comment by namedun** [comment]
Thanks for report. Fixed in 66b8457d40af4854ab3aa2108b87162d72630747.
