### ISSUE TITLE
Update source link to rrdtool

### ISSUE THREAD

**Issue by spy931** [tano-systems/meta-tanowrt#7]
Hi.
I actually try to use your meta layer (dunfell release) for building image and take error with fetchind rrdtools-1.0.50.
I checked link in your recepy:
SRC_URI = "http://oss.oetiker.ch/rrdtool/pub/rrdtool-1.0.x/rrdtool-${PV}.tar.gz"
Actual link is:
https://oss.oetiker.ch/rrdtool/pub/**archive**/rrdtool-1.0.x/

So they move old releases to archieve folder.

**Comment by namedun** [comment]
Thank you. Fixed it.
